[project]
name = "Azalea"
version = "1.0.0"
description = "DesktopPet for all students in Kivotos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "numpy",
    "openai",
    "Pillow",
    "pyautogui",
    "pydantic",
    "simpleaudio",
    "pyglet",
    "pymunk",
    "pynput",
    "PyQt6",
    "pyqt6_fluent_widgets",
    "pyqt6_sip",
    "pywin32",
    "Requests",
    "rich",
    "uvicorn>=0.52.1",
]
[project.optional-dependencies]
local = ["genie-tts", "sentence-transformers", "faiss-cpu"]
